name: Accessibility Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  a11y-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Run accessibility tests
        run: npm run test:all

      - name: Audit URLs using Lighthouse
        if: always()
        run: npm run test:lighthouse

      - name: Upload accessibility report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e-Konkursy-accessibility
          path: |
            cypress/reports/a11y
            reports/lighthouse
            wyniki

      - uses: EndBug/add-and-commit@v9
        if: always()
        with:
          add: './README.md'
          message: 'Update README.md'
